import path from "path";
import type { Config } from "tailwindcss";

const v = (name: string) => `rgb(var(--${name}) / <alpha-value>)`;

const config: Config = {
  darkMode: "class",
  content: [path.join(__dirname, "src/**/*.{ts,tsx}")],
  theme: {
    container: { center: true, padding: "1.25rem", screens: { "2xl": "1200px" } },
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        canvas: v("canvas"),
        subtle: v("subtle"),
        muted: v("muted"),
        placeholder: v("placeholder"),
        highlight: v("highlight"),
        brand: v("brand"),
        "brand-hover": v("brand-hover"),
        "brand-active": v("brand-active"),
        "brand-subtle": v("brand-subtle"),
        "on-brand": v("on-brand"),
        fg: { DEFAULT: v("fg"), secondary: v("fg-secondary"), tertiary: v("fg-tertiary"), brand: v("fg-brand") },
        line: { DEFAULT: v("line"), strong: v("line-strong") },
        focus: v("focus"),
        positive: { DEFAULT: v("positive"), subtle: v("positive-subtle") },
        confusion: { DEFAULT: v("confusion"), subtle: v("confusion-subtle") },
        frustration: { DEFAULT: v("frustration"), subtle: v("frustration-subtle") },
        speaker: { self: v("speaker-self"), other: v("speaker-other") },
        panel: { line: v("panel-line"), field: v("panel-field"), fg: { DEFAULT: v("panel-fg"), secondary: v("panel-fg-secondary"), tertiary: v("panel-fg-tertiary") } },
        scm: { line: v("scm-line"), fg: { DEFAULT: v("scm-fg"), secondary: v("scm-fg-secondary"), tertiary: v("scm-fg-tertiary") } },
        git: { added: v("git-added"), modified: v("git-modified"), deleted: v("git-deleted"), renamed: v("git-renamed") },
        tag: {
          red: { DEFAULT: v("tag-red"), subtle: v("tag-red-subtle") },
          rust: { DEFAULT: v("tag-rust"), subtle: v("tag-rust-subtle") },
          amber: { DEFAULT: v("tag-amber"), subtle: v("tag-amber-subtle") },
          yellow: { DEFAULT: v("tag-yellow"), subtle: v("tag-yellow-subtle") },
          green: { DEFAULT: v("tag-green"), subtle: v("tag-green-subtle") },
          emerald: { DEFAULT: v("tag-emerald"), subtle: v("tag-emerald-subtle") },
          teal: { DEFAULT: v("tag-teal"), subtle: v("tag-teal-subtle") },
          cyan: { DEFAULT: v("tag-cyan"), subtle: v("tag-cyan-subtle") },
          blue: { DEFAULT: v("tag-blue"), subtle: v("tag-blue-subtle") },
          indigo: { DEFAULT: v("tag-indigo"), subtle: v("tag-indigo-subtle") },
          violet: { DEFAULT: v("tag-violet"), subtle: v("tag-violet-subtle") },
          purple: { DEFAULT: v("tag-purple"), subtle: v("tag-purple-subtle") },
          pink: { DEFAULT: v("tag-pink"), subtle: v("tag-pink-subtle") },
          rose: { DEFAULT: v("tag-rose"), subtle: v("tag-rose-subtle") },
        },
        gray: { 50: "#f7f7f7", 100: "#f2f2f2", 200: "#e6e6e6", 300: "#d9d9d9", 500: "#808080", 700: "#525252", 950: "#0d0d0d" },
        surface: v("surface"),
        "surface-2": v("surface-2"),
        well: v("well"),
        ink: v("ink"),
        "ink-2": v("ink-2"),
        accent: { DEFAULT: v("accent"), strong: v("accent-strong"), tint: v("accent-tint"), fg: v("accent-fg") },
        strong: { DEFAULT: v("strong"), tint: v("strong-tint") },
        promising: { DEFAULT: v("promising"), tint: v("promising-tint") },
        weak: { DEFAULT: v("weak"), tint: v("weak-tint") },
        lowconf: { DEFAULT: v("lowconf"), tint: v("lowconf-tint") },
        capped: { DEFAULT: v("capped"), tint: v("capped-tint") },
      },
      borderRadius: { xs: "2px", sm: "4px", DEFAULT: "4px", md: "6px", lg: "8px", xl: "12px" },
      boxShadow: {
        ring: "0 0 12px rgba(0, 0, 0, 0.12)",
        card: "0 4px 44px rgba(0, 0, 0, 0.08)",
        popover: "0 8px 28px rgba(0, 0, 0, 0.07)",
        float: "0 4px 44px rgba(0, 0, 0, 0.08)",
        pop: "0 8px 28px rgba(0, 0, 0, 0.07)",
      },
      opacity: { 32: "0.32" },
      width: { sidebar: "262px" },
      height: { topnav: "66px" },
      fontSize: {
        "2xs": ["11px", "14px"],
        caption: ["10px", { lineHeight: "1.35" }],
        panel: ["11px", { lineHeight: "1.35" }],
        small: ["12px", { lineHeight: "1.5" }],
        body: ["14px", { lineHeight: "1.5" }],
        title: ["16px", { lineHeight: "1.35" }],
        heading: ["20px", { lineHeight: "1.2" }],
        "page-title": ["32px", { lineHeight: "1.2" }],
        "display-sm": ["44px", { lineHeight: "0.9" }],
        display: ["72px", { lineHeight: "0.9" }],
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "slide-in-right": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        pulse2: { "0%,100%": { opacity: "1" }, "50%": { opacity: ".45" } },
        flash: { "0%": { backgroundColor: "rgb(var(--accent-tint))" }, "100%": { backgroundColor: "transparent" } },
      },
      animation: {
        "fade-in": "fade-in .15s ease-out",
        "slide-in-right": "slide-in-right .2s ease-out",
        pulse2: "pulse2 1.4s ease-in-out infinite",
        flash: "flash 1.6s ease-out",
      },
    },
  },
  plugins: [],
};
export default config;
